# -*- coding: utf-8 -*-
"""nlp_lab_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-o-6noDS1eEWcWmYGrpj09S84ZpOo6SA
"""

!pip install gensim

from google.colab import drive
drive.mount('/content/drive')

import gensim
import re
import nltk

word2vec = gensim.models.KeyedVectors.load_word2vec_format('/content/drive/MyDrive/vectors.txt', binary=False)

pat = re.compile("(.*)_NOUN")
dist = word2vec.most_similar(positive=['радиоактивность_NOUN', 'драгоценность_NOUN'], topn=10)
for word in dist:
    e = pat.match(word[0])
    if e is not None:
        print(e.group(1))

pat = re.compile("(.*)_NOUN")
dist = word2vec.most_similar(positive=['алмаз_NOUN'], negative=['огранщик_NOUN'], topn=10)
for word in dist:
    e = pat.match(word[0])
    if e is not None:
        print(e.group(1))